version: '3.4'
services:
  api:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
      target: production
    ports:
      - 4000:4000
    env_file:
      - ../../.env.production
